//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovie.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int booking_id { get; set; }
        public Nullable<decimal> amount_paid { get; set; }
        public string payment_Type { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<int> seat_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual seat seat { get; set; }
    }
}
