//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovie.DM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMyOnlineMovieEntities : DbContext
    {
        public dbMyOnlineMovieEntities()
            : base("name=dbMyOnlineMovieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<movie> movies { get; set; }
        public virtual DbSet<movie_catagory> movie_catagory { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<seat> seats { get; set; }
        public virtual DbSet<seatCategory> seatCategories { get; set; }
        public virtual DbSet<slideImage> slideImages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
