//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovie.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class slideImage
    {
        public int SlideId { get; set; }
        public string SlideTitle { get; set; }
        public string SlideImage1 { get; set; }
    }
}
